### ISSUE TITLE
Move Pin 1 marking of RGBA LED to proper position

### ISSUE THREAD

**Issue by NKelias** [Nitrokey/nitrokey-fido2-hardware#3]
Pin 1 Marking on the PCB is currently on the position of Pin 4 on the package.
Alternatively, the anode mark between Pins 1 and 3 on the package might be used as well for alignment.

![Screenshot_20190327_175254](https://user-images.githubusercontent.com/36131955/55234345-3eab5d00-522b-11e9-876b-adcb36ca31c6.png)

Datasheet: https://everlightamericas.com/index.php?controller=attachment&id_attachment=1010

**Comment by jans23** [comment]
Fixed in revision 2.
