### ISSUE TITLE
Correct self-inducement of the touch button

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-fido2-hardware#4]
At the moment there is a chance, that the touch button press state would be induced by the blinking of the LED. LED, and/or its power lines, seem to be too close to the touch button plane, thus influencing it. When confirmed with the manual of [MTCH101] (page 9, 7.0 DETECTION DISTANCE), there is this statement: 
> No ground plane was near the sensor, as this would give the maximum
detection distance. 

At the moment this is worked around in the firmware, by increasing the touch button activation time to 1000 ms (from 500 ms).

Possible solutions:
- moving the LED,
- moving LED's power lines,
- decreasing the size of the touch button plane (optionally moving it to side).

------

Another opinion:
> The datasheet says metal components placed closed to the sensing area could cause this
effect. Actually, touch devices generally requires a "clear" space all
around the sensing area. It means no any metal component should be
closer than a few millimeters, so it is true even for the copper tracks
and therefore the gnd plane. (...)  This can be solved by both hw and sw. The
hw way means a new layout design following the capacitive design
criterias.

[MTCH101]: https://github.com/Nitrokey/nitrokey-fido-u2f-hardware/blob/master/datasheets/Microchip%20MTCH101.pdf

**Comment by jans23** [comment]
Hopefully fixed in revision 2. Should be reopened if it still occurs.
